# 1. 起始规则
<program> ::= <statement> | <statement> <program>

# 2. 语句 (Statement)
# 语句可以是变量声明、赋值语句、条件语句或循环语句。
<statement> ::= <variable_declaration> | <assignment> | <if_statement> | <while_statement>
<variable_declaration> ::= <type> <identifier> ('=' <expression>)? ';'
<assignment> ::= <identifier> '=' <expression> ';'
<if_statement> ::= 'if' '(' <expression> ')' '{' <program> '}' 
                | 'if' '(' <expression> ')' '{' <program> '}' 'else' '{' <program> '}' 
<while_statement> ::= 'while' '(' <expression> ')' '{' <program> '}'


# <expression> 是一个带值的语句
# 次高优先级：乘除法 (Term)
# 接下来，我们定义一个由“因子”通过乘除法组成的结构，称之为 <term> (项)。

<factor> ::= <number> | <identifier> | '(' <expression> ')'
<term> ::= <factor> | <term> '*' <factor> | <term> '/' <factor>
<expression> ::= <term> 
    | <expression> '+' <term> 
    | <expression> '-' <term> 
    | <expression> '>' <term> 
    | <expression> '<' <term> 

# 最高优先级：标识符和数字 (Identifier and Number)
<type> ::= 'int' | 'float' | 'string' | 'bool' | 'char'
<identifier> ::= <letter> | <identifier> <letter> | <identifier> <digit>
<number> ::= <digit> | <number> <digit>
<letter> ::= 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' 
           | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' 
           | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'
              | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J'
                | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T'
                | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '_'

<digit> ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'